// AUTO-GENERATED by SyntaxOS BackendAgent from the committed endpoint plan.
// Edit your endpoint plan + regenerate rather than hand-editing this file.
//
// Every function in this client maps 1:1 to a backend route. Frontend
// pages and IntegrationAgent should import from here instead of
// rolling their own fetch() calls.

import type { AuthSession, Booking, BookingCancellationInput, BookingCreateInput, BvnVerificationInput, CurrentUser, CustomerProfile, CustomerProfileUpdate, FlightSearch, FlightSearchInput, Installment, Itinerary, KycBrowserSession, KycSession, KycSessionCreateInput, KycStatus, KycTokenExchangeInput, LedgerEntryList, OperationalEventList, OperationsBookingList, PasswordResetConfirmation, PasswordResetRequest, Payment, PaymentIntent, PaymentIntentCreateInput, PaystackWebhookInput, QoreidWebhookInput, Quote, QuoteRevalidationInput, ReconciliationReport, RefreshTokenInput, Refund, RefundCreateInput, RepaymentSchedule, SigninInput, SignupInput, VirtualAccount, Wallet } from "@/lib/api-contracts";

export class ApiError extends Error {
  constructor(public status: number, message: string, public body?: unknown) {
    super(message);
    this.name = "ApiError";
  }
}

async function request<T>(
  method: string,
  path: string,
  body?: unknown,
  headers?: Record<string, string>,
): Promise<T> {
  const init: RequestInit = { method, headers: { ...headers } };
  if (body !== undefined) {
    init.headers = { ...init.headers, "Content-Type": "application/json" };
    init.body = JSON.stringify(body);
  }
  const res = await fetch(path, init);
  const ct = res.headers.get("content-type") || "";
  const data = ct.includes("application/json") ? await res.json() : null;
  if (!res.ok) {
    const message = (data && (data as { error?: string }).error) || res.statusText;
    throw new ApiError(res.status, message, data);
  }
  return data as T;
}

export type AgentRequestContext = {
  apiKey: string;
  whatsappNumber: string;
};

function agentHeaders(context: AgentRequestContext) {
  return {
    "X-API-Key": context.apiKey,
    "X-WhatsApp-Number": context.whatsappNumber,
  };
}

export async function getCustomerProfile(context: AgentRequestContext): Promise<CustomerProfile> {
  return request<CustomerProfile>("GET", "/api/me", undefined, agentHeaders(context));
}

export async function updateCustomerProfile(context: AgentRequestContext, body: CustomerProfileUpdate): Promise<CustomerProfile> {
  return request<CustomerProfile>("PATCH", "/api/me", body, agentHeaders(context));
}

export async function signup(body: SignupInput): Promise<AuthSession> {
  return request<AuthSession>("POST", "/api/auth/signup", body);
}

export async function login(body: SigninInput): Promise<AuthSession> {
  return request<AuthSession>("POST", "/api/auth/login", body);
}

export async function createAuthRefresh(body: RefreshTokenInput): Promise<AuthSession> {
  return request<AuthSession>("POST", "/api/auth/refresh", body);
}

export async function logout(): Promise<unknown> {
  return request<unknown>("POST", "/api/auth/logout");
}

export async function createAuthPasswordReset(body: PasswordResetRequest): Promise<unknown> {
  return request<unknown>("POST", "/api/auth/password-reset", body);
}

export async function createAuthPasswordResetConfirm(body: PasswordResetConfirmation): Promise<unknown> {
  return request<unknown>("POST", "/api/auth/password-reset/confirm", body);
}

export async function getMe(): Promise<CurrentUser> {
  return request<CurrentUser>("GET", "/api/auth/me");
}

export async function createKycSessions(context: AgentRequestContext, body: KycSessionCreateInput): Promise<KycSession> {
  return request<KycSession>("POST", "/api/kyc/sessions", body, agentHeaders(context));
}

export async function createKycSessionsExchange(body: KycTokenExchangeInput): Promise<KycBrowserSession> {
  return request<KycBrowserSession>("POST", "/api/kyc/sessions/exchange", body);
}

export async function getKycSessionsBySessionId(session_id: string, context?: AgentRequestContext): Promise<KycSession> {
  return request<KycSession>("GET", `/api/kyc/sessions/${session_id}`, undefined, context ? agentHeaders(context) : undefined);
}

export async function listMeKyc(context: AgentRequestContext): Promise<KycStatus> {
  return request<KycStatus>("GET", "/api/me/kyc", undefined, agentHeaders(context));
}

export async function createFlightsSearches(context: AgentRequestContext, body: FlightSearchInput): Promise<FlightSearch> {
  return request<FlightSearch>("POST", "/api/flights/searches", body, agentHeaders(context));
}

export async function getFlightsSearchesBySearchId(context: AgentRequestContext, search_id: string): Promise<FlightSearch> {
  return request<FlightSearch>("GET", `/api/flights/searches/${search_id}`, undefined, agentHeaders(context));
}

export async function getQuotesByQuoteId(context: AgentRequestContext, quote_id: string): Promise<Quote> {
  return request<Quote>("GET", `/api/quotes/${quote_id}`, undefined, agentHeaders(context));
}

export async function postQuotesRevalidateByQuoteId(context: AgentRequestContext, quote_id: string, body: QuoteRevalidationInput): Promise<Quote> {
  return request<Quote>("POST", `/api/quotes/${quote_id}/revalidate`, body, agentHeaders(context));
}

export async function createBookings(context: AgentRequestContext, body: BookingCreateInput): Promise<Booking> {
  return request<Booking>("POST", "/api/bookings", body, agentHeaders(context));
}

export async function getBookingsByBookingId(context: AgentRequestContext, booking_id: string): Promise<Booking> {
  return request<Booking>("GET", `/api/bookings/${booking_id}`, undefined, agentHeaders(context));
}

export async function getBookingsItineraryByBookingId(context: AgentRequestContext, booking_id: string): Promise<Itinerary> {
  return request<Itinerary>("GET", `/api/bookings/${booking_id}/itinerary`, undefined, agentHeaders(context));
}

export async function getBookingsRepaymentByBookingId(context: AgentRequestContext, booking_id: string): Promise<RepaymentSchedule> {
  return request<RepaymentSchedule>("GET", `/api/bookings/${booking_id}/repayment`, undefined, agentHeaders(context));
}

export async function listWallet(context: AgentRequestContext): Promise<Wallet> {
  return request<Wallet>("GET", "/api/wallet", undefined, agentHeaders(context));
}

export async function listWalletLedger(context: AgentRequestContext): Promise<LedgerEntryList> {
  return request<LedgerEntryList>("GET", "/api/wallet/ledger", undefined, agentHeaders(context));
}

export async function createPaymentsIntents(context: AgentRequestContext, idempotencyKey: string, body: PaymentIntentCreateInput): Promise<PaymentIntent> {
  return request<PaymentIntent>("POST", "/api/payments/intents", body, { ...agentHeaders(context), "Idempotency-Key": idempotencyKey });
}

export async function getPaymentsByPaymentId(context: AgentRequestContext, payment_id: string): Promise<Payment> {
  return request<Payment>("GET", `/api/payments/${payment_id}`, undefined, agentHeaders(context));
}

export async function postPaymentsRefundsByPaymentId(context: AgentRequestContext, payment_id: string, body: RefundCreateInput): Promise<Refund> {
  return request<Refund>("POST", `/api/payments/${payment_id}/refunds`, body, agentHeaders(context));
}

export async function getInstallmentsByInstallmentId(context: AgentRequestContext, installment_id: string): Promise<Installment> {
  return request<Installment>("GET", `/api/installments/${installment_id}`, undefined, agentHeaders(context));
}

export async function createWebhooksPaymentsPaystack(body: PaystackWebhookInput): Promise<unknown> {
  return request<unknown>("POST", "/api/webhooks/payments/paystack", body);
}

export async function createWebhooksKycQoreid(body: QoreidWebhookInput): Promise<unknown> {
  return request<unknown>("POST", "/api/webhooks/kyc/qoreid", body);
}

export async function listOperationsBookings(): Promise<OperationsBookingList> {
  return request<OperationsBookingList>("GET", "/api/operations/bookings");
}

export async function postOperationsBookingsCancelByBookingId(booking_id: string, body: BookingCancellationInput): Promise<Booking> {
  return request<Booking>("POST", `/api/operations/bookings/${booking_id}/cancel`, body);
}

export async function listOperationsReconciliation(): Promise<ReconciliationReport> {
  return request<ReconciliationReport>("GET", "/api/operations/reconciliation");
}

export async function listEvents(context: AgentRequestContext): Promise<OperationalEventList> {
  return request<OperationalEventList>("GET", "/api/events", undefined, agentHeaders(context));
}

/** Allow authenticated operations staff to mark an operational booking/case resolved, updating its status with optimistic locking semantics suitable for the operations dashboard. */
export async function postOperationsBookingsResolveByBookingId(booking_id: string): Promise<unknown> {
  return request<unknown>("POST", `/api/operations/bookings/${booking_id}/resolve`);
}

/** Record consent for a KYC verification session and initiate/open the configured identity verification provider flow after the user accepts the privacy notice. The endpoint should validate session ownership, consent timestamp, and return the provider launch state or URL. */
export async function postKycSessionsConsentBySessionId(session_id: string): Promise<unknown> {
  return request<unknown>("POST", `/api/kyc/sessions/${session_id}/consent`, { consent: true, privacy_notice_version: "1.0" });
}

export async function verifyKycBvn(session_id: string, body: BvnVerificationInput): Promise<{ status: string; virtual_account: VirtualAccount }> {
  return request<{ status: string; virtual_account: VirtualAccount }>("POST", `/api/kyc/sessions/${session_id}/verify-bvn`, body);
}
