"use client";

import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, ArrowDownRight, ArrowUpRight, Bell, Check, ChevronDown, CircleHelp, Clock3, Command, FileSearch, Filter, LayoutDashboard, LogOut, Menu, MoreHorizontal, RefreshCw, Search, Settings2, ShieldCheck, SlidersHorizontal, X, Zap } from "lucide-react";
import { getMe, listOperationsBookings, listOperationsReconciliation, logout, postOperationsBookingsCancelByBookingId } from "@/lib/api/client";
import type { Booking, CurrentUser, OperationsBookingList, ReconciliationReport } from "@/lib/api-contracts";

type CaseStatus = "Needs review" | "In progress" | "Resolved";
type CaseItem = { id: string; bookingId: string; type: string; customer: string; reference: string; age: string; status: CaseStatus; severity: "High" | "Medium" | "Low"; detail: string };
type RecordValue = Record<string, unknown>;

function asRecord(value: unknown): RecordValue { return value && typeof value === "object" ? value as RecordValue : {}; }
function text(value: unknown, fallback: string) { return typeof value === "string" || typeof value === "number" ? String(value) : fallback; }
function ageFrom(value: unknown) { if (typeof value !== "string") return "Unknown"; const minutes = Math.max(0, Math.floor((Date.now() - new Date(value).getTime()) / 60000)); return minutes < 60 ? `${minutes} min` : `${Math.floor(minutes / 60)} hr`; }
function statusFor(value: unknown): CaseStatus { const status = text(value, "").toUpperCase(); return status.includes("RESOLVED") || status === "COMPLETED" || status === "CANCELLED" ? "Resolved" : status.includes("PROGRESS") || status.includes("PENDING") ? "In progress" : "Needs review"; }
function caseFromBooking(raw: unknown, index: number): CaseItem { const b = asRecord(raw); const bookingId = text(b.id, `booking-${index + 1}`); const status = statusFor(b.status); return { bookingId, id: `OPS-${bookingId.slice(-6).toUpperCase()}`, type: text(b.booking_type, "Booking exception"), customer: text(b.customer_id, "Unknown customer"), reference: bookingId, age: ageFrom(b.created_at), status, severity: status === "Needs review" ? "High" : status === "In progress" ? "Medium" : "Low", detail: `Booking ${bookingId} is currently ${text(b.status, "awaiting review")}. Review the booking record before taking an operational action.` }; }

function Metric({ label, value, change, direction, icon: Icon, tone = "blue" }: { label: string; value: string; change: string; direction: "up" | "down"; icon: typeof Clock3; tone?: "blue" | "green" | "amber" | "red" }) { return <article className="ops-metric"><div className={`ops-metric-icon ${tone}`}><Icon size={17} /></div><div className="ops-metric-copy"><span>{label}</span><strong>{value}</strong><small className={direction === "up" ? "positive" : "negative"}>{direction === "up" ? <ArrowUpRight size={13} /> : <ArrowDownRight size={13} />}{change}</small></div></article>; }

export default function OperationsDashboard() {
  const [mobileOpen, setMobileOpen] = useState(false); const [activeNav, setActiveNav] = useState("Overview");
  const [bookings, setBookings] = useState<OperationsBookingList | null>(null); const [reconciliation, setReconciliation] = useState<ReconciliationReport | null>(null); const [me, setMe] = useState<CurrentUser | null>(null);
  const [query, setQuery] = useState(""); const [status, setStatus] = useState<"All statuses" | CaseStatus>("All statuses"); const [selected, setSelected] = useState<CaseItem | null>(null); const [toast, setToast] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [actionLoading, setActionLoading] = useState(false);

  const loadDashboard = async () => { setLoading(true); setError(""); try { const [bookingData, reconData, userData] = await Promise.all([listOperationsBookings(), listOperationsReconciliation(), getMe()]); setBookings(bookingData); setReconciliation(reconData); setMe(userData); } catch (err) { setError(err instanceof Error ? err.message : "Unable to load operations data."); } finally { setLoading(false); } };
  useEffect(() => { void loadDashboard(); }, []);

  const cases = useMemo(() => (bookings?.bookings ?? []).map(caseFromBooking), [bookings]);
  const filteredCases = useMemo(() => cases.filter((item) => `${item.id} ${item.type} ${item.customer} ${item.reference}`.toLowerCase().includes(query.toLowerCase()) && (status === "All statuses" || item.status === status)), [cases, query, status]);
  const notify = (message: string) => setToast(message);
  const refresh = () => { void loadDashboard().then(() => notify("Queue refreshed")); };
  const resolveCase = async () => { if (!selected) return; setActionLoading(true); try { await postOperationsBookingsCancelByBookingId(selected.bookingId, { reason: "Operational exception reviewed" }); setSelected(null); notify(`Command accepted for ${selected.id}`); await loadDashboard(); } catch (err) { setError(err instanceof Error ? err.message : "Unable to update this booking."); } finally { setActionLoading(false); } };
  const profile = asRecord(me?.customer); const displayName = text(profile.first_name, text(profile.name, text(me?.user && asRecord(me.user).email, "Operations staff")));
  const openCount = cases.filter((item) => item.status !== "Resolved").length; const reconTotal = reconciliation?.total ?? 0;

  return <div className="ops-app">
    <aside className={`ops-sidebar ${mobileOpen ? "open" : ""}`}>
      <div className="ops-brand"><span className="ops-brand-mark">t</span><span>tripkopa</span><button className="ops-close" onClick={() => setMobileOpen(false)} aria-label="Close navigation"><X size={18} /></button></div>
      <div className="ops-workspace"><span className="ops-workspace-label">Workspace</span><button className="ops-workspace-select" onClick={() => notify("Tripkopa operations workspace selected")}><span><span className="ops-workspace-dot" />Tripkopa operations</span><ChevronDown size={15} /></button></div>
      <nav className="ops-nav" aria-label="Operations navigation">
        <button className={activeNav === "Overview" ? "active" : ""} onClick={() => { setActiveNav("Overview"); setMobileOpen(false); }}><LayoutDashboard size={18} /><span>Overview</span></button>
        <button className={activeNav === "Review queue" ? "active" : ""} onClick={() => { setActiveNav("Review queue"); setMobileOpen(false); }}><FileSearch size={18} /><span>Review queue</span><b>{openCount}</b></button>
        <button className={activeNav === "Reconciliation" ? "active" : ""} onClick={() => { setActiveNav("Reconciliation"); setMobileOpen(false); }}><SlidersHorizontal size={18} /><span>Reconciliation</span></button>
        <button className={activeNav === "Provider health" ? "active" : ""} onClick={() => { setActiveNav("Provider health"); setMobileOpen(false); }}><Zap size={18} /><span>Provider health</span></button>
        <button className={activeNav === "Audit trail" ? "active" : ""} onClick={() => { setActiveNav("Audit trail"); setMobileOpen(false); }}><ShieldCheck size={18} /><span>Audit trail</span></button>
      </nav>
      <div className="ops-sidebar-bottom"><button onClick={() => notify("Settings are available to administrators")}><Settings2 size={17} />Settings</button><button onClick={() => notify("Help request opened")}><CircleHelp size={17} />Help center</button><div className="ops-profile"><div className="ops-avatar">{displayName.slice(0, 2).toUpperCase()}</div><div><strong>{displayName}</strong><span>Operations agent</span></div><button aria-label="Profile menu" onClick={() => notify("Profile menu opened")}><MoreHorizontal size={17} /></button></div></div>
    </aside>
    <main className="ops-main"><header className="ops-topbar"><button className="ops-menu" onClick={() => setMobileOpen(true)} aria-label="Open navigation"><Menu size={21} /></button><div className="ops-breadcrumb"><span>Operations</span><span>/</span><strong>{activeNav}</strong></div><div className="ops-top-actions"><div className="ops-correlation"><Command size={14} /> <span>Live session</span></div><button className="ops-icon-button" onClick={() => notify("No new operational alerts")} aria-label="Notifications"><Bell size={18} /><i /></button><button className="ops-signout" onClick={async () => { try { await logout(); window.location.assign("/login"); } catch (err) { setError(err instanceof Error ? err.message : "Unable to sign out."); } }}><LogOut size={16} />Sign out</button></div></header>
      <div className="ops-content"><div className="ops-page-heading"><div><div className="ops-eyebrow"><span />Operational control plane</div><h1>Good morning, {displayName}.</h1><p>Resolve exceptions, protect the ledger, and keep every journey moving.</p></div><button className="ops-refresh" onClick={refresh} disabled={loading}>{loading ? <span className="ops-spinner" /> : <RefreshCw size={16} />}{loading ? "Refreshing" : "Refresh queue"}</button></div>
        {error && <div className="ops-error" role="alert">{error}</div>}
        <section className="ops-metrics" aria-label="Operational metrics"><Metric label="Open review cases" value={loading ? "—" : String(openCount)} change="From live bookings" direction="down" icon={FileSearch} tone="amber" /><Metric label="Reconciliation records" value={loading ? "—" : String(reconTotal)} change="From live ledger report" direction="up" icon={ShieldCheck} tone="green" /><Metric label="Provider availability" value="—" change="No provider health endpoint" direction="up" icon={Zap} tone="blue" /><Metric label="Loaded bookings" value={loading ? "—" : String(bookings?.total ?? 0)} change="Current operations feed" direction="up" icon={Clock3} tone="green" /></section>
        <section className="ops-grid"><article className="ops-card ops-queue-card"><div className="ops-card-header"><div><span className="ops-card-kicker">Work queue</span><h2>Cases requiring attention</h2></div><button className="ops-quiet-button" onClick={() => { setStatus("All statuses"); setQuery(""); notify("Queue filters cleared"); }}>Clear filters</button></div><div className="ops-toolbar"><div className="ops-search"><Search size={16} /><input aria-label="Search cases" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search case, customer or reference" /></div><div className="ops-filter"><Filter size={15} /><select aria-label="Filter by status" value={status} onChange={(e) => setStatus(e.target.value as "All statuses" | CaseStatus)}><option>All statuses</option><option>Needs review</option><option>In progress</option><option>Resolved</option></select></div></div><div className="ops-table-wrap"><table className="ops-table"><thead><tr><th>Case</th><th>Customer / reference</th><th>Age</th><th>Status</th><th /></tr></thead><tbody>{filteredCases.map((item) => <tr key={item.bookingId} onClick={() => setSelected(item)} tabIndex={0} onKeyDown={(e) => e.key === "Enter" && setSelected(item)}><td><div className="ops-case-id"><span className={`ops-severity ${item.severity.toLowerCase()}`} /><strong>{item.id}</strong></div><small>{item.type}</small></td><td><strong>{item.customer}</strong><small>{item.reference}</small></td><td><span className="ops-age"><Clock3 size={13} />{item.age}</span></td><td><span className={`ops-status ${item.status.toLowerCase().replace(" ", "-")}`}>{item.status}</span></td><td><button className="ops-row-action" onClick={(e) => { e.stopPropagation(); setSelected(item); }} aria-label={`Open ${item.id}`}><MoreHorizontal size={17} /></button></td></tr>)}{!loading && filteredCases.length === 0 && <tr><td colSpan={5}><div className="ops-empty"><FileSearch size={22} /><strong>No cases match these filters</strong><span>Try a different search or clear the current filters.</span></div></td></tr>}</tbody></table></div><div className="ops-card-footer"><span>Showing {filteredCases.length} of {cases.length} cases</span><button onClick={() => { setActiveNav("Review queue"); notify("Review queue selected"); }}>View all cases <ArrowUpRight size={14} /></button></div></article>
          <aside className="ops-side-stack"><article className="ops-card ops-health-card"><div className="ops-card-header"><div><span className="ops-card-kicker">Connections</span><h2>Provider health</h2></div><button className="ops-icon-button small" onClick={refresh} aria-label="Refresh provider health"><RefreshCw size={15} /></button></div><div className="ops-provider-list"><div className="ops-provider"><span className="ops-provider-status" /><div><strong>Provider health unavailable</strong><small>No provider health API is exposed</small></div><code>—</code></div></div><button className="ops-full-button" onClick={() => { setActiveNav("Provider health"); notify("Provider health selected"); }}>View provider health <ArrowUpRight size={14} /></button></article><article className="ops-card ops-recon-card"><div className="ops-card-header"><div><span className="ops-card-kicker">Ledger integrity</span><h2>Reconciliation</h2></div><span className="ops-check-pill"><Check size={13} /> {reconciliation ? "Loaded" : "Loading"}</span></div><div className="ops-recon-value">{reconciliation ? reconciliation.total : "—"} <span>records</span></div><div className="ops-recon-track"><span /></div><div className="ops-recon-meta"><span>Live report</span><span>{reconciliation?.total ?? 0} entries</span></div><button className="ops-full-button" onClick={() => { setActiveNav("Reconciliation"); notify("Reconciliation selected"); }}>Open reconciliation <ArrowUpRight size={14} /></button></article></aside></section>
        <div className="ops-footer-note"><ShieldCheck size={15} /><span>Staff actions are permissioned and recorded by the operations API.</span><button onClick={() => { setActiveNav("Audit trail"); notify("Audit trail selected"); }}>Inspect audit trail <ArrowUpRight size={14} /></button></div>
      </div></main>
    {selected && <div className="ops-modal-backdrop" role="presentation" onMouseDown={() => setSelected(null)}><section className="ops-modal" role="dialog" aria-modal="true" aria-labelledby="case-title" onMouseDown={(e) => e.stopPropagation()}><div className="ops-modal-head"><div><span className="ops-card-kicker">Case detail · {selected.id}</span><h2 id="case-title">{selected.type}</h2></div><button className="ops-icon-button" onClick={() => setSelected(null)} aria-label="Close case detail"><X size={18} /></button></div><div className="ops-modal-summary"><div><span>Customer</span><strong>{selected.customer}</strong></div><div><span>Reference</span><strong>{selected.reference}</strong></div><div><span>Severity</span><strong>{selected.severity}</strong></div></div><div className="ops-modal-callout"><AlertTriangle size={18} /><p>{selected.detail}</p></div><div className="ops-modal-actions"><button className="ops-secondary-button" onClick={() => { setSelected(null); notify("Case kept open"); }}>Keep open</button><button className="ops-primary-button" onClick={resolveCase} disabled={actionLoading}><Check size={16} />{actionLoading ? "Updating" : "Request cancellation"}</button></div><small className="ops-modal-footnote">This action is sent to the operations API and may require further processing.</small></section></div>}
    {toast && <button className="ops-toast" role="status" onClick={() => setToast("")}><Check size={16} />{toast}</button>}
  </div>;
}
