-- AUTO-GENERATED by SyntaxOS migration_generator from contract.json entities.
-- Source of truth: the pre-flight endpoint plan's declared entities
-- (tables, typed columns, ownership, relations) — NOT route scraping.
-- Baseline columns (id, created_at, updated_at) are added automatically.
--
-- Safe to re-run: every statement uses IF NOT EXISTS / OR REPLACE, and
-- foreign keys are added via DROP CONSTRAINT IF EXISTS + ADD CONSTRAINT.

CREATE EXTENSION IF NOT EXISTS pgcrypto;  -- for gen_random_uuid()

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ─── bookings ────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.bookings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  customer_id UUID NOT NULL,
  quote_id UUID NOT NULL,
  booking_type TEXT NOT NULL,
  status TEXT NOT NULL,
  provider_reference TEXT,
  currency TEXT NOT NULL,
  total_amount NUMERIC NOT NULL,
  deposit_amount NUMERIC,
  amount_paid NUMERIC NOT NULL,
  balance_amount NUMERIC NOT NULL,
  rule_version TEXT NOT NULL,
  passengers JSONB NOT NULL,
  flight_details JSONB NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS bookings_customer_id_idx ON public.bookings(customer_id);

DROP TRIGGER IF EXISTS bookings_set_updated_at ON public.bookings;
CREATE TRIGGER bookings_set_updated_at BEFORE UPDATE ON public.bookings FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS bookings_owner_read ON public.bookings;
CREATE POLICY bookings_owner_read ON public.bookings FOR SELECT USING (auth.uid() = customer_id);
DROP POLICY IF EXISTS bookings_owner_insert ON public.bookings;
CREATE POLICY bookings_owner_insert ON public.bookings FOR INSERT WITH CHECK (auth.uid() = customer_id);
DROP POLICY IF EXISTS bookings_owner_update ON public.bookings;
CREATE POLICY bookings_owner_update ON public.bookings FOR UPDATE USING (auth.uid() = customer_id) WITH CHECK (auth.uid() = customer_id);
DROP POLICY IF EXISTS bookings_owner_delete ON public.bookings;
CREATE POLICY bookings_owner_delete ON public.bookings FOR DELETE USING (auth.uid() = customer_id);

-- ─── customers ───────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.customers (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL,
  whatsapp_number TEXT NOT NULL,
  status TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS customers_user_id_idx ON public.customers(user_id);

DROP TRIGGER IF EXISTS customers_set_updated_at ON public.customers;
CREATE TRIGGER customers_set_updated_at BEFORE UPDATE ON public.customers FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS customers_owner_read ON public.customers;
CREATE POLICY customers_owner_read ON public.customers FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS customers_owner_insert ON public.customers;
CREATE POLICY customers_owner_insert ON public.customers FOR INSERT WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS customers_owner_update ON public.customers;
CREATE POLICY customers_owner_update ON public.customers FOR UPDATE USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS customers_owner_delete ON public.customers;
CREATE POLICY customers_owner_delete ON public.customers FOR DELETE USING (auth.uid() = user_id);

-- ─── flight_searches ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.flight_searches (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  customer_id UUID NOT NULL,
  origin TEXT NOT NULL,
  destination TEXT NOT NULL,
  departure_date DATE NOT NULL,
  return_date DATE,
  trip_type TEXT NOT NULL,
  passenger_count INTEGER NOT NULL,
  cabin_class TEXT NOT NULL,
  status TEXT NOT NULL,
  results JSONB NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS flight_searches_customer_id_idx ON public.flight_searches(customer_id);

DROP TRIGGER IF EXISTS flight_searches_set_updated_at ON public.flight_searches;
CREATE TRIGGER flight_searches_set_updated_at BEFORE UPDATE ON public.flight_searches FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.flight_searches ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS flight_searches_owner_read ON public.flight_searches;
CREATE POLICY flight_searches_owner_read ON public.flight_searches FOR SELECT USING (auth.uid() = customer_id);
DROP POLICY IF EXISTS flight_searches_owner_insert ON public.flight_searches;
CREATE POLICY flight_searches_owner_insert ON public.flight_searches FOR INSERT WITH CHECK (auth.uid() = customer_id);
DROP POLICY IF EXISTS flight_searches_owner_update ON public.flight_searches;
CREATE POLICY flight_searches_owner_update ON public.flight_searches FOR UPDATE USING (auth.uid() = customer_id) WITH CHECK (auth.uid() = customer_id);
DROP POLICY IF EXISTS flight_searches_owner_delete ON public.flight_searches;
CREATE POLICY flight_searches_owner_delete ON public.flight_searches FOR DELETE USING (auth.uid() = customer_id);

-- ─── installments ────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.installments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  customer_id UUID NOT NULL,
  booking_id UUID NOT NULL,
  sequence_number INTEGER NOT NULL,
  due_date DATE NOT NULL,
  amount NUMERIC NOT NULL,
  paid_amount NUMERIC NOT NULL,
  status TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS installments_customer_id_idx ON public.installments(customer_id);

DROP TRIGGER IF EXISTS installments_set_updated_at ON public.installments;
CREATE TRIGGER installments_set_updated_at BEFORE UPDATE ON public.installments FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.installments ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS installments_owner_read ON public.installments;
CREATE POLICY installments_owner_read ON public.installments FOR SELECT USING (auth.uid() = customer_id);
DROP POLICY IF EXISTS installments_owner_insert ON public.installments;
CREATE POLICY installments_owner_insert ON public.installments FOR INSERT WITH CHECK (auth.uid() = customer_id);
DROP POLICY IF EXISTS installments_owner_update ON public.installments;
CREATE POLICY installments_owner_update ON public.installments FOR UPDATE USING (auth.uid() = customer_id) WITH CHECK (auth.uid() = customer_id);
DROP POLICY IF EXISTS installments_owner_delete ON public.installments;
CREATE POLICY installments_owner_delete ON public.installments FOR DELETE USING (auth.uid() = customer_id);

-- ─── itineraries ─────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.itineraries (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  customer_id UUID NOT NULL,
  booking_id UUID NOT NULL,
  release_level TEXT NOT NULL,
  segments JSONB NOT NULL,
  ticket_reference TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS itineraries_customer_id_idx ON public.itineraries(customer_id);

DROP TRIGGER IF EXISTS itineraries_set_updated_at ON public.itineraries;
CREATE TRIGGER itineraries_set_updated_at BEFORE UPDATE ON public.itineraries FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.itineraries ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS itineraries_owner_read ON public.itineraries;
CREATE POLICY itineraries_owner_read ON public.itineraries FOR SELECT USING (auth.uid() = customer_id);
DROP POLICY IF EXISTS itineraries_owner_insert ON public.itineraries;
CREATE POLICY itineraries_owner_insert ON public.itineraries FOR INSERT WITH CHECK (auth.uid() = customer_id);
DROP POLICY IF EXISTS itineraries_owner_update ON public.itineraries;
CREATE POLICY itineraries_owner_update ON public.itineraries FOR UPDATE USING (auth.uid() = customer_id) WITH CHECK (auth.uid() = customer_id);
DROP POLICY IF EXISTS itineraries_owner_delete ON public.itineraries;
CREATE POLICY itineraries_owner_delete ON public.itineraries FOR DELETE USING (auth.uid() = customer_id);

-- ─── kyc_sessions ────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.kyc_sessions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  customer_id UUID NOT NULL,
  provider TEXT NOT NULL,
  status TEXT NOT NULL,
  provider_reference TEXT,
  token_hash TEXT NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  used_at TIMESTAMPTZ,
  normalized_result JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS kyc_sessions_customer_id_idx ON public.kyc_sessions(customer_id);

DROP TRIGGER IF EXISTS kyc_sessions_set_updated_at ON public.kyc_sessions;
CREATE TRIGGER kyc_sessions_set_updated_at BEFORE UPDATE ON public.kyc_sessions FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.kyc_sessions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS kyc_sessions_owner_read ON public.kyc_sessions;
CREATE POLICY kyc_sessions_owner_read ON public.kyc_sessions FOR SELECT USING (auth.uid() = customer_id);
DROP POLICY IF EXISTS kyc_sessions_owner_insert ON public.kyc_sessions;
CREATE POLICY kyc_sessions_owner_insert ON public.kyc_sessions FOR INSERT WITH CHECK (auth.uid() = customer_id);
DROP POLICY IF EXISTS kyc_sessions_owner_update ON public.kyc_sessions;
CREATE POLICY kyc_sessions_owner_update ON public.kyc_sessions FOR UPDATE USING (auth.uid() = customer_id) WITH CHECK (auth.uid() = customer_id);
DROP POLICY IF EXISTS kyc_sessions_owner_delete ON public.kyc_sessions;
CREATE POLICY kyc_sessions_owner_delete ON public.kyc_sessions FOR DELETE USING (auth.uid() = customer_id);

-- ─── ledger_entries ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.ledger_entries (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  customer_id UUID NOT NULL,
  wallet_id UUID NOT NULL,
  payment_id UUID,
  booking_id UUID,
  entry_type TEXT NOT NULL,
  amount NUMERIC NOT NULL,
  currency TEXT NOT NULL,
  status TEXT NOT NULL,
  description TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ledger_entries_customer_id_idx ON public.ledger_entries(customer_id);

DROP TRIGGER IF EXISTS ledger_entries_set_updated_at ON public.ledger_entries;
CREATE TRIGGER ledger_entries_set_updated_at BEFORE UPDATE ON public.ledger_entries FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.ledger_entries ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS ledger_entries_owner_read ON public.ledger_entries;
CREATE POLICY ledger_entries_owner_read ON public.ledger_entries FOR SELECT USING (auth.uid() = customer_id);
DROP POLICY IF EXISTS ledger_entries_owner_insert ON public.ledger_entries;
CREATE POLICY ledger_entries_owner_insert ON public.ledger_entries FOR INSERT WITH CHECK (auth.uid() = customer_id);
DROP POLICY IF EXISTS ledger_entries_owner_update ON public.ledger_entries;
CREATE POLICY ledger_entries_owner_update ON public.ledger_entries FOR UPDATE USING (auth.uid() = customer_id) WITH CHECK (auth.uid() = customer_id);
DROP POLICY IF EXISTS ledger_entries_owner_delete ON public.ledger_entries;
CREATE POLICY ledger_entries_owner_delete ON public.ledger_entries FOR DELETE USING (auth.uid() = customer_id);

-- ─── operational_events ──────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.operational_events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  customer_id UUID NOT NULL,
  booking_id UUID,
  event_type TEXT NOT NULL,
  payload JSONB NOT NULL,
  delivered_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS operational_events_customer_id_idx ON public.operational_events(customer_id);

DROP TRIGGER IF EXISTS operational_events_set_updated_at ON public.operational_events;
CREATE TRIGGER operational_events_set_updated_at BEFORE UPDATE ON public.operational_events FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.operational_events ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS operational_events_authenticated_read ON public.operational_events;
CREATE POLICY operational_events_authenticated_read ON public.operational_events FOR SELECT USING (auth.role() = 'authenticated');
DROP POLICY IF EXISTS operational_events_owner_insert ON public.operational_events;
CREATE POLICY operational_events_owner_insert ON public.operational_events FOR INSERT WITH CHECK (auth.uid() = customer_id);
DROP POLICY IF EXISTS operational_events_owner_update ON public.operational_events;
CREATE POLICY operational_events_owner_update ON public.operational_events FOR UPDATE USING (auth.uid() = customer_id) WITH CHECK (auth.uid() = customer_id);
DROP POLICY IF EXISTS operational_events_owner_delete ON public.operational_events;
CREATE POLICY operational_events_owner_delete ON public.operational_events FOR DELETE USING (auth.uid() = customer_id);

-- ─── payments ────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.payments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  customer_id UUID NOT NULL,
  booking_id UUID,
  provider TEXT NOT NULL,
  provider_reference TEXT,
  payment_type TEXT NOT NULL,
  amount NUMERIC NOT NULL,
  currency TEXT NOT NULL,
  status TEXT NOT NULL,
  checkout_url TEXT,
  metadata JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS payments_customer_id_idx ON public.payments(customer_id);

DROP TRIGGER IF EXISTS payments_set_updated_at ON public.payments;
CREATE TRIGGER payments_set_updated_at BEFORE UPDATE ON public.payments FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS payments_owner_read ON public.payments;
CREATE POLICY payments_owner_read ON public.payments FOR SELECT USING (auth.uid() = customer_id);
DROP POLICY IF EXISTS payments_owner_insert ON public.payments;
CREATE POLICY payments_owner_insert ON public.payments FOR INSERT WITH CHECK (auth.uid() = customer_id);
DROP POLICY IF EXISTS payments_owner_update ON public.payments;
CREATE POLICY payments_owner_update ON public.payments FOR UPDATE USING (auth.uid() = customer_id) WITH CHECK (auth.uid() = customer_id);
DROP POLICY IF EXISTS payments_owner_delete ON public.payments;
CREATE POLICY payments_owner_delete ON public.payments FOR DELETE USING (auth.uid() = customer_id);

-- ─── provider_webhooks ───────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.provider_webhooks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  provider TEXT NOT NULL,
  event_type TEXT NOT NULL,
  provider_event_id TEXT NOT NULL,
  payload JSONB NOT NULL,
  processing_status TEXT NOT NULL,
  processed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

DROP TRIGGER IF EXISTS provider_webhooks_set_updated_at ON public.provider_webhooks;
CREATE TRIGGER provider_webhooks_set_updated_at BEFORE UPDATE ON public.provider_webhooks FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.provider_webhooks ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS provider_webhooks_authenticated_read ON public.provider_webhooks;
CREATE POLICY provider_webhooks_authenticated_read ON public.provider_webhooks FOR SELECT USING (auth.role() = 'authenticated');
DROP POLICY IF EXISTS provider_webhooks_authenticated_insert ON public.provider_webhooks;
CREATE POLICY provider_webhooks_authenticated_insert ON public.provider_webhooks FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- ─── quotes ──────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.quotes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  customer_id UUID NOT NULL,
  search_id UUID NOT NULL,
  provider TEXT NOT NULL,
  provider_reference TEXT NOT NULL,
  currency TEXT NOT NULL,
  base_amount NUMERIC NOT NULL,
  total_amount NUMERIC NOT NULL,
  deposit_amount NUMERIC,
  installment_amount NUMERIC,
  rule_version TEXT NOT NULL,
  version INTEGER NOT NULL,
  status TEXT NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  details JSONB NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS quotes_customer_id_idx ON public.quotes(customer_id);

DROP TRIGGER IF EXISTS quotes_set_updated_at ON public.quotes;
CREATE TRIGGER quotes_set_updated_at BEFORE UPDATE ON public.quotes FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.quotes ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS quotes_owner_read ON public.quotes;
CREATE POLICY quotes_owner_read ON public.quotes FOR SELECT USING (auth.uid() = customer_id);
DROP POLICY IF EXISTS quotes_owner_insert ON public.quotes;
CREATE POLICY quotes_owner_insert ON public.quotes FOR INSERT WITH CHECK (auth.uid() = customer_id);
DROP POLICY IF EXISTS quotes_owner_update ON public.quotes;
CREATE POLICY quotes_owner_update ON public.quotes FOR UPDATE USING (auth.uid() = customer_id) WITH CHECK (auth.uid() = customer_id);
DROP POLICY IF EXISTS quotes_owner_delete ON public.quotes;
CREATE POLICY quotes_owner_delete ON public.quotes FOR DELETE USING (auth.uid() = customer_id);

-- ─── reconciliation_records ──────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.reconciliation_records (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  provider TEXT NOT NULL,
  payment_id UUID,
  provider_reference TEXT,
  status TEXT NOT NULL,
  difference NUMERIC,
  details JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

DROP TRIGGER IF EXISTS reconciliation_records_set_updated_at ON public.reconciliation_records;
CREATE TRIGGER reconciliation_records_set_updated_at BEFORE UPDATE ON public.reconciliation_records FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.reconciliation_records ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS reconciliation_records_authenticated_read ON public.reconciliation_records;
CREATE POLICY reconciliation_records_authenticated_read ON public.reconciliation_records FOR SELECT USING (auth.role() = 'authenticated');
DROP POLICY IF EXISTS reconciliation_records_authenticated_insert ON public.reconciliation_records;
CREATE POLICY reconciliation_records_authenticated_insert ON public.reconciliation_records FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- ─── refunds ─────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.refunds (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  customer_id UUID NOT NULL,
  payment_id UUID NOT NULL,
  booking_id UUID,
  provider_reference TEXT,
  amount NUMERIC NOT NULL,
  currency TEXT NOT NULL,
  status TEXT NOT NULL,
  reason TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS refunds_customer_id_idx ON public.refunds(customer_id);

DROP TRIGGER IF EXISTS refunds_set_updated_at ON public.refunds;
CREATE TRIGGER refunds_set_updated_at BEFORE UPDATE ON public.refunds FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.refunds ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS refunds_owner_read ON public.refunds;
CREATE POLICY refunds_owner_read ON public.refunds FOR SELECT USING (auth.uid() = customer_id);
DROP POLICY IF EXISTS refunds_owner_insert ON public.refunds;
CREATE POLICY refunds_owner_insert ON public.refunds FOR INSERT WITH CHECK (auth.uid() = customer_id);
DROP POLICY IF EXISTS refunds_owner_update ON public.refunds;
CREATE POLICY refunds_owner_update ON public.refunds FOR UPDATE USING (auth.uid() = customer_id) WITH CHECK (auth.uid() = customer_id);
DROP POLICY IF EXISTS refunds_owner_delete ON public.refunds;
CREATE POLICY refunds_owner_delete ON public.refunds FOR DELETE USING (auth.uid() = customer_id);

-- ─── staff_profiles ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.staff_profiles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL,
  role TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS staff_profiles_user_id_idx ON public.staff_profiles(user_id);

DROP TRIGGER IF EXISTS staff_profiles_set_updated_at ON public.staff_profiles;
CREATE TRIGGER staff_profiles_set_updated_at BEFORE UPDATE ON public.staff_profiles FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.staff_profiles ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS staff_profiles_owner_read ON public.staff_profiles;
CREATE POLICY staff_profiles_owner_read ON public.staff_profiles FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS staff_profiles_owner_insert ON public.staff_profiles;
CREATE POLICY staff_profiles_owner_insert ON public.staff_profiles FOR INSERT WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS staff_profiles_owner_update ON public.staff_profiles;
CREATE POLICY staff_profiles_owner_update ON public.staff_profiles FOR UPDATE USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS staff_profiles_owner_delete ON public.staff_profiles;
CREATE POLICY staff_profiles_owner_delete ON public.staff_profiles FOR DELETE USING (auth.uid() = user_id);

-- ─── wallets ─────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.wallets (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  customer_id UUID NOT NULL,
  currency TEXT NOT NULL,
  balance NUMERIC NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS wallets_customer_id_idx ON public.wallets(customer_id);

DROP TRIGGER IF EXISTS wallets_set_updated_at ON public.wallets;
CREATE TRIGGER wallets_set_updated_at BEFORE UPDATE ON public.wallets FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.wallets ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS wallets_owner_read ON public.wallets;
CREATE POLICY wallets_owner_read ON public.wallets FOR SELECT USING (auth.uid() = customer_id);
DROP POLICY IF EXISTS wallets_owner_insert ON public.wallets;
CREATE POLICY wallets_owner_insert ON public.wallets FOR INSERT WITH CHECK (auth.uid() = customer_id);
DROP POLICY IF EXISTS wallets_owner_update ON public.wallets;
CREATE POLICY wallets_owner_update ON public.wallets FOR UPDATE USING (auth.uid() = customer_id) WITH CHECK (auth.uid() = customer_id);
DROP POLICY IF EXISTS wallets_owner_delete ON public.wallets;
CREATE POLICY wallets_owner_delete ON public.wallets FOR DELETE USING (auth.uid() = customer_id);

-- ─── foreign keys (deferred so table order never matters) ─────────
ALTER TABLE public.bookings DROP CONSTRAINT IF EXISTS bookings_customer_id_fkey;
ALTER TABLE public.bookings ADD CONSTRAINT bookings_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id) ON DELETE CASCADE;
ALTER TABLE public.bookings DROP CONSTRAINT IF EXISTS bookings_quote_id_fkey;
ALTER TABLE public.bookings ADD CONSTRAINT bookings_quote_id_fkey FOREIGN KEY (quote_id) REFERENCES public.quotes(id) ON DELETE CASCADE;
ALTER TABLE public.customers DROP CONSTRAINT IF EXISTS customers_user_id_fkey;
ALTER TABLE public.customers ADD CONSTRAINT customers_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.flight_searches DROP CONSTRAINT IF EXISTS flight_searches_customer_id_fkey;
ALTER TABLE public.flight_searches ADD CONSTRAINT flight_searches_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id) ON DELETE CASCADE;
ALTER TABLE public.installments DROP CONSTRAINT IF EXISTS installments_customer_id_fkey;
ALTER TABLE public.installments ADD CONSTRAINT installments_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id) ON DELETE CASCADE;
ALTER TABLE public.installments DROP CONSTRAINT IF EXISTS installments_booking_id_fkey;
ALTER TABLE public.installments ADD CONSTRAINT installments_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id) ON DELETE CASCADE;
ALTER TABLE public.itineraries DROP CONSTRAINT IF EXISTS itineraries_customer_id_fkey;
ALTER TABLE public.itineraries ADD CONSTRAINT itineraries_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id) ON DELETE CASCADE;
ALTER TABLE public.itineraries DROP CONSTRAINT IF EXISTS itineraries_booking_id_fkey;
ALTER TABLE public.itineraries ADD CONSTRAINT itineraries_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id) ON DELETE CASCADE;
ALTER TABLE public.kyc_sessions DROP CONSTRAINT IF EXISTS kyc_sessions_customer_id_fkey;
ALTER TABLE public.kyc_sessions ADD CONSTRAINT kyc_sessions_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id) ON DELETE CASCADE;
ALTER TABLE public.ledger_entries DROP CONSTRAINT IF EXISTS ledger_entries_customer_id_fkey;
ALTER TABLE public.ledger_entries ADD CONSTRAINT ledger_entries_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id) ON DELETE CASCADE;
ALTER TABLE public.ledger_entries DROP CONSTRAINT IF EXISTS ledger_entries_wallet_id_fkey;
ALTER TABLE public.ledger_entries ADD CONSTRAINT ledger_entries_wallet_id_fkey FOREIGN KEY (wallet_id) REFERENCES public.wallets(id) ON DELETE CASCADE;
ALTER TABLE public.ledger_entries DROP CONSTRAINT IF EXISTS ledger_entries_payment_id_fkey;
ALTER TABLE public.ledger_entries ADD CONSTRAINT ledger_entries_payment_id_fkey FOREIGN KEY (payment_id) REFERENCES public.payments(id) ON DELETE CASCADE;
ALTER TABLE public.ledger_entries DROP CONSTRAINT IF EXISTS ledger_entries_booking_id_fkey;
ALTER TABLE public.ledger_entries ADD CONSTRAINT ledger_entries_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id) ON DELETE CASCADE;
ALTER TABLE public.operational_events DROP CONSTRAINT IF EXISTS operational_events_customer_id_fkey;
ALTER TABLE public.operational_events ADD CONSTRAINT operational_events_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id) ON DELETE CASCADE;
ALTER TABLE public.operational_events DROP CONSTRAINT IF EXISTS operational_events_booking_id_fkey;
ALTER TABLE public.operational_events ADD CONSTRAINT operational_events_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id) ON DELETE CASCADE;
ALTER TABLE public.payments DROP CONSTRAINT IF EXISTS payments_customer_id_fkey;
ALTER TABLE public.payments ADD CONSTRAINT payments_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id) ON DELETE CASCADE;
ALTER TABLE public.payments DROP CONSTRAINT IF EXISTS payments_booking_id_fkey;
ALTER TABLE public.payments ADD CONSTRAINT payments_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id) ON DELETE CASCADE;
ALTER TABLE public.quotes DROP CONSTRAINT IF EXISTS quotes_customer_id_fkey;
ALTER TABLE public.quotes ADD CONSTRAINT quotes_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id) ON DELETE CASCADE;
ALTER TABLE public.quotes DROP CONSTRAINT IF EXISTS quotes_search_id_fkey;
ALTER TABLE public.quotes ADD CONSTRAINT quotes_search_id_fkey FOREIGN KEY (search_id) REFERENCES public.flight_searches(id) ON DELETE CASCADE;
ALTER TABLE public.reconciliation_records DROP CONSTRAINT IF EXISTS reconciliation_records_payment_id_fkey;
ALTER TABLE public.reconciliation_records ADD CONSTRAINT reconciliation_records_payment_id_fkey FOREIGN KEY (payment_id) REFERENCES public.payments(id) ON DELETE CASCADE;
ALTER TABLE public.refunds DROP CONSTRAINT IF EXISTS refunds_customer_id_fkey;
ALTER TABLE public.refunds ADD CONSTRAINT refunds_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id) ON DELETE CASCADE;
ALTER TABLE public.refunds DROP CONSTRAINT IF EXISTS refunds_payment_id_fkey;
ALTER TABLE public.refunds ADD CONSTRAINT refunds_payment_id_fkey FOREIGN KEY (payment_id) REFERENCES public.payments(id) ON DELETE CASCADE;
ALTER TABLE public.refunds DROP CONSTRAINT IF EXISTS refunds_booking_id_fkey;
ALTER TABLE public.refunds ADD CONSTRAINT refunds_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id) ON DELETE CASCADE;
ALTER TABLE public.staff_profiles DROP CONSTRAINT IF EXISTS staff_profiles_user_id_fkey;
ALTER TABLE public.staff_profiles ADD CONSTRAINT staff_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.wallets DROP CONSTRAINT IF EXISTS wallets_customer_id_fkey;
ALTER TABLE public.wallets ADD CONSTRAINT wallets_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id) ON DELETE CASCADE;
